server:
  port: 9111


spring:
  application:
    name: chapter-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: springcloud-front-service9100
    prefer-ip-address: true
